[workspace]
members = [ "application","domain", "pokedex"]

[workspace. Dependencies]
# We will add all our common dependent crates for our sub crates to share
# the same version. How cool is that :D
