[package]
name = "learn_006_rust_lang_org"
version = "0.1.0"
edition = "2021"
authors = ["david"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "cap01"
path = "src/cap01/main.rs"
