apiVersion: apps/v1
kind: Deployment
metadata:
  name: actor-server
  namespace: actor-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actor-server
  template:
    metadata:
      labels:
        app: actor-server
    spec:
      containers:
        - name: actor-server
          image: actor_server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: actor-server-service
  namespace: actor-demo
spec:
  selector:
    app: actor-server
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
  type: ClusterIP

