services:
  sail-server:
    image: sail
    command: spark server --ip 0.0.0.0 --port 50051
    ports:
      - "50051:50051"
    networks:
      - sail-net

    #environment:
    #  - RUST_LOG=debug

    working_dir: /stage
    volumes:
      - ./data:/stage

  pyspark-client:
    image: python:3.11-slim
    container_name: pyspark-client
    depends_on:
      - sail-server
    networks:
      - sail-net
    working_dir: /app
    volumes:
      - ./client:/app
    command: >
      sh -c "pip install -r requirements.txt && python client.py"
    environment:
      - PYTHONUNBUFFERED=1

networks:
  sail-net:
    driver: bridge
